#! /usr/bin/env bash
set -e # stop the execution of the script if it fails

FUNC_DIR="cruddur-messaging-stream/"
TEMPLATE_PATH="template.yaml"

# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
# --use-container
# use container is for building the lambda in a container
# it's still using the runtimes and its not a custom runtime
sam build \
--use-container \
--template $TEMPLATE_PATH \
--base-dir $FUNC_DIR
#--parameter-overrides