#!/bin/bash
ARTIFACT_BUCKET="cfn-artifacts.cruddur.myhomelab.xyz"
TEMPLATE_PATH=".aws-sam/build/template.yaml"
OUTPUT_TEMPLATE_PATH=".aws-sam/build/packaged.yaml"

sam package \
  --s3-bucket $ARTIFACT_BUCKET \
  --output-template-file $OUTPUT_TEMPLATE_PATH \
  --template-file $TEMPLATE_PATH \
  --s3-prefix "ddb"