AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ClusterStack:
    Type: String
    Default: cruddur-cluster
Resources:
  API:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Sub ${AWS::StackName}-Avatar-Upload
      ProtocolType: HTTP
      RouteSelectionExpression: $request.method $request.path
      ApiKeySelectionExpression: $request.header.x-api-key
      DisableExecuteApiEndpoint: False
AvatarUploadRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref API
    AuthorizationType: CUSTOM
    AuthorizerId: !Ref Authorizer
    RouteKey: 'POST /avatars/key_upload'
    Target: !Join 
      - /
      - - integrations
        - !Ref MyIntegration
ProxyRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref API
    AuthorizationType: NONE
    RouteKey: 'OPTIONS /{proxy+}'
    Target: !Join 
      - /
      - - integrations
        - !Ref MyIntegration