AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPC:
    Type: AWS::EC2::VPC
  Properties:
    CidrBlock:
    EnableDnsHostnames: true
    EnableDnsSupport: true
    InstanceTenancy: default
# VPC
# IGW
# Route Tables
# Subnets
  # A
  # B
  # C