AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CertificateArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cruddur/certificateArn
  FrontendBucketName:
    Type: String
    Default: frontend.cruddur.myhomelab.xyz
  FrontendDomain:
    Type: String
    Default: cruddur.myhomelab.xyz
  HostedZoneID:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cruddur/route53/zoneID
Resources:
  RootBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RootBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${RootBucket}/*'
            Principal: '*'
  RootBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      BucketName: !Ref FrontendBucketName
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  RootBucketDomain:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneID
      Name: !Ref FrontendDomain
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref FrontendDomain
        Comment: Frontend for Cruddur
        Enabled: true
        HttpVersion: http2and3 
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - DomainName: !GetAtt RootBucket.DomainName
            Id: RootBucketOrigin
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: RootBucketOrigin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
Outputs:
  RootBucketName:
    Value: !Ref RootBucket
    Export:
      Name: !Sub "${AWS::StackName}RootBucketName"
  DistributionId:
    Value: !Ref Distribution
    Export:
      Name: !Sub "${AWS::StackName}DistributionId"